### ISSUE TITLE
インストールエラー cannot use int(commentID) (type int) as type int64 in argument

### ISSUE THREAD

**Issue by officel** [mercari/tfnotify#1]
```
$ go get -u github.com/mercari/tfnotify
# github.com/mercari/tfnotify/notifier/github
/home/vagrant/go/src/github.com/mercari/tfnotify/notifier/github/github.go:31:64: cannot use int(commentID) (type int) as type int64 in argument to g.Client.Issues.DeleteComment

$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

$ uname -a
Linux dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ go version
go version go1.9 linux/amd64
```
Windows 7 上の Vagrant で VirtualBox で CentOS 7.3 で go get したらエラーになってしまいます。

まだ go1.10 では試していません。

**Comment by officel** [comment]
go 1.10 でも同様でした。。。

**Comment by b4b4r07** [comment]
手元の go-github が古いせいだと思います。

```console
$ git clone https://github.com/mercari/tfnotify && cd tfnotify
$ dep ensure
$ go build
```

dep で vendoring してあるバージョンの go-github を使ってみてください。

**Comment by officel** [comment]
ありがとうございます。確認できました。

**Comment by yagi5** [comment]
## Plan result <sup>[CI link]( https://circleci.com/gh/yagi5/msmini-terraform/25 )</sup>
terraform/microservices/item

<pre><code> Plan: 2 to add, 0 to change, 0 to destroy.
</pre></code>

<details><summary>Details (Click me)</summary>
<pre><code> Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  &#43; create

Terraform will perform the following actions:

  &#43; module.item-service.google_project.microservice
      id:                  &lt;computed&gt;
      auto_create_network: &#34;true&#34;
      folder_id:           &lt;computed&gt;
      name:                &#34;msmini-item&#34;
      number:              &lt;computed&gt;
      org_id:              &lt;computed&gt;
      policy_data:         &lt;computed&gt;
      policy_etag:         &lt;computed&gt;
      project_id:          &#34;msmini-item&#34;
      skip_delete:         &#34;false&#34;

  &#43; module.item-service.google_project_iam_member.microservice_service_admins
      id:                  &lt;computed&gt;
      etag:                &lt;computed&gt;
      member:              &#34;user:ygnmhdtt@gmail.com&#34;
      project:             &#34;msmini-item&#34;
      role:                &#34;roles/editor&#34;


Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn&#39;t specify an &#34;-out&#34; parameter to save this plan, so Terraform
can&#39;t guarantee that exactly these actions will be performed if
&#34;terraform apply&#34; is subsequently run.


</pre></code></details>

**Comment by ToshihitoKon** [comment]
## Plan result




<pre><code>Plan: 14 to add, 0 to change, 0 to destroy.
</code></pre>


<details><summary>Details (Click me)</summary>

<pre><code>Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  &#43; create

Terraform will perform the following actions:

  # aws_cloudwatch_log_group.nginx will be created
  &#43; resource &#34;aws_cloudwatch_log_group&#34; &#34;nginx&#34; {
      &#43; arn               = (known after apply)
      &#43; id                = (known after apply)
      &#43; name              = &#34;/ecs/ecs-train-nginx&#34;
      &#43; retention_in_days = 0
    }

  # aws_ecr_repository.ecs-train will be created
  &#43; resource &#34;aws_ecr_repository&#34; &#34;ecs-train&#34; {
      &#43; arn                  = (known after apply)
      &#43; id                   = (known after apply)
      &#43; image_tag_mutability = &#34;MUTABLE&#34;
      &#43; name                 = &#34;tennichi/ecs-train&#34;
      &#43; registry_id          = (known after apply)
      &#43; repository_url       = (known after apply)

      &#43; image_scanning_configuration {
          &#43; scan_on_push = false
        }

      &#43; timeouts {}
    }

  # aws_ecs_cluster.ecs-train will be created
  &#43; resource &#34;aws_ecs_cluster&#34; &#34;ecs-train&#34; {
      &#43; arn                = (known after apply)
      &#43; capacity_providers = [
          &#43; &#34;FARGATE&#34;,
          &#43; &#34;FARGATE_SPOT&#34;,
        ]
      &#43; id                 = (known after apply)
      &#43; name               = &#34;ecs-train&#34;

      &#43; setting {
          &#43; name  = &#34;containerInsights&#34;
          &#43; value = &#34;disabled&#34;
        }
    }

  # aws_iam_role.exec will be created
  &#43; resource &#34;aws_iam_role&#34; &#34;exec&#34; {
      &#43; arn                   = (known after apply)
      &#43; assume_role_policy    = jsonencode(
            {
              &#43; Statement = [
                  &#43; {
                      &#43; Action    = &#34;sts:AssumeRole&#34;
                      &#43; Effect    = &#34;Allow&#34;
                      &#43; Principal = {
                          &#43; Service = &#34;ecs-tasks.amazonaws.com&#34;
                        }
                      &#43; Sid       = &#34;&#34;
                    },
                ]
              &#43; Version   = &#34;2012-10-17&#34;
            }
        )
      &#43; create_date           = (known after apply)
      &#43; description           = &#34;for ecs train created by tennichi&#34;
      &#43; force_detach_policies = false
      &#43; id                    = (known after apply)
      &#43; max_session_duration  = 3600
      &#43; name                  = &#34;ecs-train&#34;
      &#43; path                  = &#34;/&#34;
      &#43; unique_id             = (known after apply)
    }

  # aws_iam_role_policy_attachment.ecr-read will be created
  &#43; resource &#34;aws_iam_role_policy_attachment&#34; &#34;ecr-read&#34; {
      &#43; id         = (known after apply)
      &#43; policy_arn = &#34;arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly&#34;
      &#43; role       = &#34;ecs-train&#34;
    }

  # aws_iam_role_policy_attachment.log-write will be created
  &#43; resource &#34;aws_iam_role_policy_attachment&#34; &#34;log-write&#34; {
      &#43; id         = (known after apply)
      &#43; policy_arn = &#34;arn:aws:iam::aws:policy/CloudWatchLogsFullAccess&#34;
      &#43; role       = &#34;ecs-train&#34;
    }

  # aws_internet_gateway.igw will be created
  &#43; resource &#34;aws_internet_gateway&#34; &#34;igw&#34; {
      &#43; id       = (known after apply)
      &#43; owner_id = (known after apply)
      &#43; tags     = {
          &#43; &#34;Name&#34; = &#34;ecs-train&#34;
        }
      &#43; vpc_id   = (known after apply)
    }

  # aws_route_table.subnet-route-table will be created
  &#43; resource &#34;aws_route_table&#34; &#34;subnet-route-table&#34; {
      &#43; id               = (known after apply)
      &#43; owner_id         = (known after apply)
      &#43; propagating_vgws = (known after apply)
      &#43; route            = [
          &#43; {
              &#43; cidr_block                = &#34;0.0.0.0/0&#34;
              &#43; egress_only_gateway_id    = &#34;&#34;
              &#43; gateway_id                = (known after apply)
              &#43; instance_id               = &#34;&#34;
              &#43; ipv6_cidr_block           = &#34;&#34;
              &#43; nat_gateway_id            = &#34;&#34;
              &#43; network_interface_id      = &#34;&#34;
              &#43; transit_gateway_id        = &#34;&#34;
              &#43; vpc_peering_connection_id = &#34;&#34;
            },
        ]
      &#43; tags             = {
          &#43; &#34;Name&#34; = &#34;ecs-train&#34;
        }
      &#43; vpc_id           = (known after apply)
    }

  # aws_route_table_association.subnet-0 will be created
  &#43; resource &#34;aws_route_table_association&#34; &#34;subnet-0&#34; {
      &#43; id             = (known after apply)
      &#43; route_table_id = (known after apply)
      &#43; subnet_id      = (known after apply)
    }

  # aws_route_table_association.subnet-1 will be created
  &#43; resource &#34;aws_route_table_association&#34; &#34;subnet-1&#34; {
      &#43; id             = (known after apply)
      &#43; route_table_id = (known after apply)
      &#43; subnet_id      = (known after apply)
    }

  # aws_security_group.sg will be created
  &#43; resource &#34;aws_security_group&#34; &#34;sg&#34; {
      &#43; arn                    = (known after apply)
      &#43; description            = &#34;2020-05-12T06:55:27.374Z&#34;
      &#43; egress                 = [
          &#43; {
              &#43; cidr_blocks      = [
                  &#43; &#34;0.0.0.0/0&#34;,
                ]
              &#43; description      = &#34;&#34;
              &#43; from_port        = 0
              &#43; ipv6_cidr_blocks = []
              &#43; prefix_list_ids  = []
              &#43; protocol         = &#34;-1&#34;
              &#43; security_groups  = []
              &#43; self             = false
              &#43; to_port          = 0
            },
        ]
      &#43; id                     = (known after apply)
      &#43; ingress                = [
          &#43; {
              &#43; cidr_blocks      = [
                  &#43; &#34;0.0.0.0/0&#34;,
                ]
              &#43; description      = &#34;&#34;
              &#43; from_port        = 80
              &#43; ipv6_cidr_blocks = []
              &#43; prefix_list_ids  = []
              &#43; protocol         = &#34;tcp&#34;
              &#43; security_groups  = []
              &#43; self             = false
              &#43; to_port          = 80
            },
        ]
      &#43; name                   = &#34;ecs-train-nginx&#34;
      &#43; owner_id               = (known after apply)
      &#43; revoke_rules_on_delete = false
      &#43; vpc_id                 = (known after apply)
    }

  # aws_subnet.subnet-0 will be created
  &#43; resource &#34;aws_subnet&#34; &#34;subnet-0&#34; {
      &#43; arn                             = (known after apply)
      &#43; assign_ipv6_address_on_creation = false
      &#43; availability_zone               = &#34;ap-northeast-1a&#34;
      &#43; availability_zone_id            = (known after apply)
      &#43; cidr_block                      = &#34;10.0.0.0/24&#34;
      &#43; id                              = (known after apply)
      &#43; ipv6_cidr_block                 = (known after apply)
      &#43; ipv6_cidr_block_association_id  = (known after apply)
      &#43; map_public_ip_on_launch         = false
      &#43; owner_id                        = (known after apply)
      &#43; tags                            = {
          &#43; &#34;Name&#34; = &#34;ecs-train/Public&#34;
        }
      &#43; vpc_id                          = (known after apply)
    }

  # aws_subnet.subnet-1 will be created
  &#43; resource &#34;aws_subnet&#34; &#34;subnet-1&#34; {
      &#43; arn                             = (known after apply)
      &#43; assign_ipv6_address_on_creation = false
      &#43; availability_zone               = &#34;ap-northeast-1c&#34;
      &#43; availability_zone_id            = (known after apply)
      &#43; cidr_block                      = &#34;10.0.1.0/24&#34;
      &#43; id                              = (known after apply)
      &#43; ipv6_cidr_block                 = (known after apply)
      &#43; ipv6_cidr_block_association_id  = (known after apply)
      &#43; map_public_ip_on_launch         = false
      &#43; owner_id                        = (known after apply)
      &#43; tags                            = {
          &#43; &#34;Name&#34; = &#34;ecs-train/Public&#34;
        }
      &#43; vpc_id                          = (known after apply)
    }

  # aws_vpc.vpc will be created
  &#43; resource &#34;aws_vpc&#34; &#34;vpc&#34; {
      &#43; arn                              = (known after apply)
      &#43; assign_generated_ipv6_cidr_block = false
      &#43; cidr_block                       = &#34;10.0.0.0/16&#34;
      &#43; default_network_acl_id           = (known after apply)
      &#43; default_route_table_id           = (known after apply)
      &#43; default_security_group_id        = (known after apply)
      &#43; dhcp_options_id                  = (known after apply)
      &#43; enable_classiclink               = false
      &#43; enable_classiclink_dns_support   = false
      &#43; enable_dns_hostnames             = true
      &#43; enable_dns_support               = true
      &#43; id                               = (known after apply)
      &#43; instance_tenancy                 = &#34;default&#34;
      &#43; ipv6_association_id              = (known after apply)
      &#43; ipv6_cidr_block                  = (known after apply)
      &#43; main_route_table_id              = (known after apply)
      &#43; owner_id                         = (known after apply)
      &#43; tags                             = {
          &#43; &#34;Name&#34; = &#34;ecs-train&#34;
        }
    }

Plan: 14 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn&#39;t specify an &#34;-out&#34; parameter to save this plan, so Terraform
can&#39;t guarantee that exactly these actions will be performed if
&#34;terraform apply&#34; is subsequently run.


</code></pre></details>
