### ISSUE TITLE
Support TeamCity

### ISSUE THREAD

**Issue by genert** [mercari/tfnotify#29]
TeamCity is quite popular among other CIs - https://www.jetbrains.com/teamcity/

See #28 PR for implementation.

**Comment by omerlh** [comment]
I found a workaround - configure TF notify with `ci: circleci` and then just use env var to define the PR:
```
export set CIRCLE_PULL_REQUEST=1
```

**Comment by b4b4r07** [comment]
https://github.com/mercari/tfnotify/pull/28 was just merged. So this was finally achieved. Thank you for your contribution.
