### ISSUE TITLE
Document required GitHub permissions

### ISSUE THREAD

**Issue by TomFaulkner** [mercari/tfnotify#8]
It might be beneficial to include the required permissions in the readme. It seems to be that they are `repo` and `write:discussion` at least for private repos.

**Comment by b4b4r07** [comment]
>It might be beneficial to include the required permissions in the readme

What is this permission?

**Comment by b4b4r07** [comment]
>That should be all that is needed, I believe.

OK, but what are the `repo` and `write:discussion`? Are these something like token?

**Comment by TomFaulkner** [comment]
They are permissions here: https://github.com/settings/tokens

**Comment by b4b4r07** [comment]
OK. Would you give me pull-request?

**Comment by b4b4r07** [comment]
Thank you. #12 was just merged.
